org: jonathanamarante
service: lection-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./sls/config/env.yml)}
  iam:
    role: ${file(./sls/config/role.yml)}
  httpApi:
    # disableDefaultEndpoint: ${env:DISABLE_DEFAULT_APIGW_ENDPOINT, false} == 'true'
    cors:
      allowedOrigins:
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowCredentials: true
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPool.ProviderURL
        audience:
          - !Ref UserPoolClient

package:
  individually: true

custom:
  cognito:
    PoolName: ${self:service}-${self:provider.stage}-UserPool

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(sls/functions/auth.yml)}
  - ${file(sls/functions/profiles.yml)}
  - ${file(sls/functions/questions.yml)}
  - ${file(sls/functions/dailyTexts.yml)}
  
resources:
  - ${file(./sls/resources/APIGWCustomDomain.yml)}
  - ${file(./sls/resources/UserPool.yml)}
  - ${file(./sls/resources/MainTable.yml)}
  - ${file(./sls/resources/DailyQuestionsQueue.yml)}
  - ${file(./sls/resources/DailyTextsQueue.yml)}
  - ${file(./sls/resources/DLQAlarmsTopic.yml)}
  # - ${file(./sls/resources/AIFilesBucket.yml)}
  # - ${file(./sls/resources/AIFilesBucketCDN.yml)}