statements:
  - Effect: "Allow"
    Action:
      - "dynamodb:PutItem"
      - "dynamodb:Query"
      - "dynamodb:GetItem"
      - "dynamodb:UpdateItem"
      - "dynamodb:DeleteItem"
    Resource:
      - !GetAtt MainTable.Arn
      - !Sub "${MainTable.Arn}/index/*"
  - Effect: "Allow"
    Action: cognito-idp:AdminDeleteUser
    Resource: !GetAtt UserPool.Arn
  # - Effect: "Allow"
  #   Action:
  #     - "s3:PutObject"
  #     - "s3:GetObject"
  #   Resource: !Sub '${AIFilesBucket.Arn}/*'
  - Effect: Allow
    Action: sqs:SendMessage
    Resource: !GetAtt DailyQuestionsQueue.Arn
  - Effect: Allow
    Action: sqs:SendMessage
    Resource: !GetAtt DailyTextsQueue.Arn