export enum ErrorCode {
  VALIDATION = "VALIDATION",
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
  USERNAME_ALREADY_IN_USE = "USERNAME_ALREADY_IN_USE",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

  // HTTP
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
}
